CREATE TABLE IF NOT EXISTS server_event
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    creation_time TIMESTAMP,
    CONSTRAINT pk_serverevent PRIMARY KEY (id)
);